### ISSUE TITLE
Certain settings and seed value cause Hookshot to freeze game upon firing

### ISSUE THREAD

**Issue by thefellow3j** [fenhl/OoT-Randomizer#13]
For this combination of settings and seed, firing the hookshot freezes the game. 

Version: 7.1.70 Fenhl-14
Settings string: EACSQSKAWCHGA9L62AN5LTDDSY7QAMUGBAEAAEQ7VL7ZMA6289LR9AA6AL2DATJJCXSFUBPND6JHCUTNFPTMAD3NGYKR8VAPJJLUWWFXKRLYYFQ3MA52LYVFPL542YY3PRD6CH3TQXV7UH7PR6M96ZAQSEWBT2E8TVEFMKPQV6WH93SLWDPKP4VCXK7L9RAAAB6S9VEAT8FA6KATFKR
Seed: V8N0YWE172

**Comment by thefellow3j** [comment]
This was played on RetroArch using the Mupen64 core.

**Comment by fenhl** [comment]
Did you patch this seed offline? If so, please check to make sure your patcher is on version 7.1.62 or newer.

**Comment by thefellow3j** [comment]
Is this patcher version different from the version number in the lower left corner of the GUI? I see 7.1.70 Fenhl-14 in that location.

Also, here's the spoiler file for reference:
[OoT_75749_V8N0YWE172_Spoiler.zip](https://github.com/fenhl/OoT-Randomizer/files/10899889/OoT_75749_V8N0YWE172_Spoiler.zip)

**Comment by fenhl** [comment]
Versions below 7.1.83 had cosmetics bugs that have since been fixed. If this issue happens again on a newer version of the randomizer, please post a comment and I will reopen the issue.
