### ISSUE TITLE
Crashing when rendering some ice traps

### ISSUE THREAD

**Issue by guigop2** [fenhl/OoT-Randomizer#15]
Version 7.1.118 Fenhl-17

  ":settings_string":          "EALSQSKAWCHGAHK62AEMMPDDSY7YAEAEH4AJAAACJPAE4JZBA637AA4RE6A2EWKAAAAAAAJS9RAJB6V8VAN9EA2USFA",

  ":seed":                    
 "NYBSTYHRV0",

seems whenever a skulltula that contains an ice trap is killed, i crash immediately. so far it has happened at :

    "Market GS Guard House":                                {"item": "Ice Trap", "model": "Ocarina"},

    "DMT GS Falling Rocks Path":                            {"item": "Ice Trap", "model": "Light Arrows"},

played on wii vc

**Comment by fenhl** [comment]
This doesn't seem to be limited to gold skulltula locations. [Seed 1413860](https://ootrandomizer.com/seed/get?id=1413860) crashes when loading the upper part of Zora River, which has an ice trap on the freestanding heart piece.

**Comment by guigop2** [comment]
"HC GS Storms Grotto":                                  {"item": "Ice Trap", "model": "Progressive Wallet"},

heres another one. btw botw feels really laggy in this seed

**Comment by fenhl** [comment]
Findings so far:

* Seems to be independent of emulator, or at least BizHawk crashes as well.
* Not all ice trap models crash the game when being loaded, e.g. setting the freestandings in Saria's house to ice traps cloaked as hover boots doesn't crash.
* However, it seems that ice traps that don't crash don't get cloaked correctly, e.g. the Saria's ice traps are displayed as recovery hearts and not as hover boots.
* The issue does not occur on main Dev.

From this, my guess is that I somehow broke something related to ice trap cloaks, and different types of locations either react by rendering the wrong model or crashing.

**Comment by guigop2** [comment]
yeah heres another one that isnt gold skulltula

    "Hideout 1 Torch Jail Gerudo Key":                      {"item": "Ice Trap", "model": "Small Key (Shadow Temple)"},

**Comment by guigop2** [comment]
also not just botw, but a lot of the dungeons seem to lag a lot. not like usual vc/n64 lag is this consequence of the settings?

**Comment by fenhl** [comment]
The lag is most likely unrelated.

**Comment by fenhl** [comment]
Thanks to @mracsys for [identifying the cause and providing a fix](https://github.com/OoTRandomizer/OoT-Randomizer/pull/1871#pullrequestreview-1485132274).
