### ISSUE TITLE
Bombchu drops not working correctly

### ISSUE THREAD

**Issue by XenoWars** [fenhl/OoT-Randomizer#8]
Bombchu drops appear to not add to your total when you pick them up. All other drops work correctly.

**Comment by fenhl** [comment]
On which version did you have this issue? I merged a fix for this earlier today.

**Comment by XenoWars** [comment]
We genned with 6.2.206 about 10 hours ago

**Comment by fenhl** [comment]
This was fixed in 6.2.216 Fenhl-2.
